/**
 * @file prodaq_err.h
 * @author your name (you@domain.com)
 * @brief 
 * @version 0.1
 * @date 2023-02-16
 * 
 * @copyright Copyright (c) 2023
 * 
 */

#ifndef __PRODAQ_ERR__H__
#define __PRODAQ_ERR__H__

typedef enum
{
    PRODAQ_OK = 0x0,
    PRODAQ_ERR_BASE = 0x100,
    PRODAQ_ERR_NOT_IMPLEMENTED,
    PRODAQ_ERR_INVALID_ARG,
    PRODAQ_ERR_INVALID_MESSAGE_ID,
    PRODAQ_ERR_INVALID_TYPE,
    PRODAQ_ERR_NOT_FOUND,
    PRODAQ_ERR_INVALID_SIZE,
    PRODAQ_ERR_WRITE_OPERATION_FAILED,
    PRODAQ_ERR_READ_OPERATION_FAILED,

    PRODAQ_ERR_HTTP_BASE = 0x200,
    PRODAQ_ERR_HTTP_INIT,
    PRODAQ_ERR_HTTP_SOCKET_CREATE,
    PRODAQ_ERR_HTTP_SOCKET_BIND,
    PRODAQ_ERR_HTTP_SOCKET_LISTEN,
    PRODAQ_ERR_HTTP_CONNECTION_FAIL,
    PRODAQ_ERR_HTTP_RECEIVE,
    PRODAQ_ERR_HTTP_REQUEST_PARSE_FAIL,
    PRODAQ_ERR_HTTP_SEND_RESPONSE_FAIL,
    PRODAQ_ERR_HTTP_NOT_FOUND,
    PRODAQ_ERR_HTTP_NULL_REQUEST_HANDLER,
} prodaq_err_t;

#endif  //!__PRODAQ_ERR__H__